# Use custom format

format = """
[╭─](bold green)$all
[└─>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the newline at the start of the prompt
add_newline = false

[line_break]
disabled = true
